org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

mod_version=1.21.1-1.3.0
maven_group=net.pastek.cobblemonextrastructures
archives_base_name=cobblemonextrastructures

fabric_version=0.116.0+1.21.1