## Launcher Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.93
neo_version_range=[21.1.0,)
loader_version_range=[4,)
jei_version=19.21.0.246

## Mod Properties
mod_id=cobblemonextrastructures
mod_name=Cobblemon: Extra Structures
mod_license=All Rights Reserved
mod_version=1.21.1-1.3.0
mod_group_id=net.pastek.cobblemon_extrastructures
mod_authors=Roi Pasteque
mod_description=More structures, less boring.
